package:
  name: myconda
  version: "1.0.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/SalahBioPhysics/testingconda.git 

requirements:
  build:
    - gcc testing123.c -o foo

  run:
    - python 2.7*
    - pyqt
    - numpy
    - gcc

